//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPage.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/AplicacionWebServicePOO")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaDiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JornadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pregunta1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pregunta2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TelContacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TemperaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autoriza {
            get {
                return this.AutorizaField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorizaField, value) != true)) {
                    this.AutorizaField = value;
                    this.RaisePropertyChanged("Autoriza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaDia {
            get {
                return this.FechaDiaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaDiaField, value) != true)) {
                    this.FechaDiaField = value;
                    this.RaisePropertyChanged("FechaDia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEmpleado {
            get {
                return this.IDEmpleadoField;
            }
            set {
                if ((this.IDEmpleadoField.Equals(value) != true)) {
                    this.IDEmpleadoField = value;
                    this.RaisePropertyChanged("IDEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jornada {
            get {
                return this.JornadaField;
            }
            set {
                if ((object.ReferenceEquals(this.JornadaField, value) != true)) {
                    this.JornadaField = value;
                    this.RaisePropertyChanged("Jornada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivo {
            get {
                return this.MotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoField, value) != true)) {
                    this.MotivoField = value;
                    this.RaisePropertyChanged("Motivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pregunta1 {
            get {
                return this.Pregunta1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Pregunta1Field, value) != true)) {
                    this.Pregunta1Field = value;
                    this.RaisePropertyChanged("Pregunta1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pregunta2 {
            get {
                return this.Pregunta2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Pregunta2Field, value) != true)) {
                    this.Pregunta2Field = value;
                    this.RaisePropertyChanged("Pregunta2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TelContac {
            get {
                return this.TelContacField;
            }
            set {
                if ((this.TelContacField.Equals(value) != true)) {
                    this.TelContacField = value;
                    this.RaisePropertyChanged("TelContac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Temperatura {
            get {
                return this.TemperaturaField;
            }
            set {
                if ((this.TemperaturaField.Equals(value) != true)) {
                    this.TemperaturaField = value;
                    this.RaisePropertyChanged("Temperatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmpleado", ReplyAction="http://tempuri.org/IService1/GetEmpleadoResponse")]
        WebPage.ServiceReference1.Empleado GetEmpleado(int IDEmpleado, long TelContac, decimal Temperatura, string Jornada, string Usuario, string Nombres, string Autoriza, string Motivo, string FechaDia, string Pregunta1, string Pregunta2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmpleado", ReplyAction="http://tempuri.org/IService1/GetEmpleadoResponse")]
        System.Threading.Tasks.Task<WebPage.ServiceReference1.Empleado> GetEmpleadoAsync(int IDEmpleado, long TelContac, decimal Temperatura, string Jornada, string Usuario, string Nombres, string Autoriza, string Motivo, string FechaDia, string Pregunta1, string Pregunta2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebPage.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebPage.ServiceReference1.IService1>, WebPage.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebPage.ServiceReference1.Empleado GetEmpleado(int IDEmpleado, long TelContac, decimal Temperatura, string Jornada, string Usuario, string Nombres, string Autoriza, string Motivo, string FechaDia, string Pregunta1, string Pregunta2) {
            return base.Channel.GetEmpleado(IDEmpleado, TelContac, Temperatura, Jornada, Usuario, Nombres, Autoriza, Motivo, FechaDia, Pregunta1, Pregunta2);
        }
        
        public System.Threading.Tasks.Task<WebPage.ServiceReference1.Empleado> GetEmpleadoAsync(int IDEmpleado, long TelContac, decimal Temperatura, string Jornada, string Usuario, string Nombres, string Autoriza, string Motivo, string FechaDia, string Pregunta1, string Pregunta2) {
            return base.Channel.GetEmpleadoAsync(IDEmpleado, TelContac, Temperatura, Jornada, Usuario, Nombres, Autoriza, Motivo, FechaDia, Pregunta1, Pregunta2);
        }
    }
}
